DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS FRIENDSHIP CASCADE;

CREATE TABLE PERSON (
    ID   int NOT NULL,
    Name varchar(255) NOT NULL,

    PRIMARY KEY(ID)
);

CREATE TABLE FRIENDSHIP (
    PersonId int NOT NULL,
    FriendId int NOT NULL,

    FOREIGN KEY(PersonId) REFERENCES PERSON(ID),
    FOREIGN KEY(FriendId) REFERENCES PERSON(ID)
);
